name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Check build errors
      run: dotnet build /p:TreatWarningsAsErrors=true /warnaserror
    - name: Test
      run: dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings
    - name: Install, run dotnet-outdated
      run: |
        dotnet tool install --global dotnet-outdated-tool
        dotnet outdated -f
    # Having enough trouble with this, going to look into SonarLint as an alternative
    # - name: Publish Code Coverage
    #   uses: paambaati/codeclimate-action@v5.0.0
    #   with:
    #     coverageLocations: ${{ github.workspace }}/AdventOfCode.Tests/TestResults/**/*.xml:cobertura
    #     prefix: /${{ github.workspace }}
    #   env:
    #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
